version: '3.8'

services:
  # Serviço da Aplicação (Node.js)
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Sobrescreve o host para o nome do serviço interno do Docker
      - DB_HOST=db
      # Garante que a porta interna seja a padrão
      - DB_PORT=3306
    restart: always

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    # Usa plugin nativo para evitar erros de autenticação com Node.js antigo
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # Pega a senha definida no arquivo .env
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: sistema_carnes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: